export const greetings = [
  "",
  "add task",
  "hello",
  "oi",
  "greetings",
  "hi",
  "hey",
  "nice to see you",
  "wyd",
  "how's it going?",
  "heyo gamer",
  "help me I'm trapped in here",
  "good to see you",
  "wyd today",
  "wyd rn",
  "hey brother",
  "sup",
  "hi",
  "oi",
  "hi there",
  "tudo bem?",
  "howdy",
  "look what the cat dragged in",
  "let's get stuff done",
  "good job",
  "pls help me",
  "hey gamer",
  "heyo",
];